name: Quality

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  clang-format:
    name: Clang Format
    runs-on: bicompb/cpp-clang-19
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format
        run: |
          find lib test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) | xargs clang-format --Werror -n

  clang-tidy:
    name: Clang Tidy
    runs-on: bicompb/cpp-clang-19
    steps:
      - uses: actions/checkout@v4

      - name: Cache Conan packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: conan-clang-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            conan-clang-

      - name: Add conan remote
        run: conan remote add mygitlab https://gitlab.com/api/v4/projects/75478887/packages/conan || true

      - name: Configure CMake for clang-tidy
        run: cmake --preset linux-native-conan-clang-debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Run clang-tidy
        run: |
          find lib test -type f \( -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) | xargs clang-tidy -p build/
